# Generated by Django 4.2.2 on 2023-12-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseBarrio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('zona', models.CharField(max_length=20)),
                ('cod_zona', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'base_barrio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseCentros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disp', models.CharField(max_length=24)),
                ('bod', models.CharField(max_length=24)),
                ('drogueria', models.CharField(max_length=128)),
                ('correo_coordinador', models.CharField(blank=True, max_length=128, null=True)),
                ('dia_ped', models.CharField(blank=True, max_length=24, null=True)),
                ('estado', models.CharField(blank=True, max_length=24, null=True)),
                ('modalidad', models.CharField(max_length=24)),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=24)),
                ('correo_disp', models.CharField(blank=True, max_length=128, null=True)),
                ('responsable', models.CharField(blank=True, max_length=128, null=True)),
                ('cedula', models.CharField(blank=True, max_length=64, null=True)),
                ('celular', models.CharField(blank=True, max_length=64, null=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('medicar', models.CharField(blank=True, max_length=8, null=True)),
                ('tent', models.IntegerField()),
                ('analista', models.CharField(blank=True, max_length=128, null=True)),
                ('ult_fecha_disp', models.DateTimeField(blank=True, null=True)),
                ('aux_pqr', models.CharField(blank=True, max_length=128, null=True)),
                ('transp_1', models.CharField(blank=True, max_length=128, null=True)),
                ('transp_2', models.CharField(blank=True, max_length=128, null=True)),
                ('correo_contacto_eps', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'base_centros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseInventario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('centro', models.CharField(max_length=24)),
                ('cod_mol', models.CharField(max_length=24)),
                ('cod_barra', models.CharField(max_length=128)),
                ('cum', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('lote', models.CharField(max_length=24)),
                ('fecha_vencimiento', models.DateField()),
                ('inventario', models.IntegerField()),
                ('costo_promedio', models.IntegerField()),
                ('cantidad_empaque', models.IntegerField()),
            ],
            options={
                'db_table': 'base_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseMedControlado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cum', models.CharField(max_length=24)),
                ('nombre', models.CharField(max_length=250)),
                ('activo', models.BooleanField()),
                ('field_one', models.CharField(blank=True, max_length=24, null=True)),
                ('field_two', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'base_med_controlado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseMunicipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('departamento', models.CharField(max_length=128)),
                ('activo', models.BooleanField()),
                ('cod_dane', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseRadicacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('numero_radicado', models.CharField(max_length=24, unique=True)),
                ('cel_uno', models.CharField(blank=True, max_length=24, null=True)),
                ('cel_dos', models.CharField(blank=True, max_length=24, null=True)),
                ('email', models.CharField(max_length=254)),
                ('direccion', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField()),
                ('paciente_nombre', models.CharField(max_length=150)),
                ('paciente_cc', models.CharField(max_length=32)),
                ('paciente_data', models.JSONField()),
                ('domiciliario_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('domiciliario_ide', models.CharField(blank=True, max_length=25, null=True)),
                ('domiciliario_empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=64, null=True)),
                ('alistamiento', models.DateTimeField(blank=True, null=True)),
                ('alistado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('despachado', models.DateTimeField(blank=True, null=True)),
                ('acta_entrega', models.CharField(blank=True, max_length=150, null=True)),
                ('factura', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'base_radicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturasProcesadas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agregado', models.DateTimeField()),
                ('actualizado', models.DateTimeField()),
                ('factura', models.CharField(max_length=24, unique=True)),
                ('fecha_factura', models.DateTimeField()),
                ('acta', models.CharField(max_length=24)),
                ('numero_autorizacion', models.CharField(max_length=24, unique=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('link_soporte', models.CharField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, max_length=128, null=True)),
                ('resp_cajacopi', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas_procesadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroMigracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.CharField(max_length=24)),
            ],
            options={
                'db_table': 'sap_registro_migracion',
            },
        ),
    ]
